language: csharp
solution: DiffSharp.sln

# sudo to install packages
sudo: required 

before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libopenblas-dev -y

os:
  - linux
mono:
  - latest
script:
  - ./build.sh

notifications:
  email:
    on_success: never
    on_failure: change
