language: csharp
solution: DiffSharp.sln
os:
  - linux
mono:
  - latest
script:
  - sudo apt-get -y update
  - sudo apt-get -y install libopenblas-dev
  - ./build.sh
notifications:
  email:
    on_success: never
    on_failure: change
